UPDATE items SET icon_name = 'great_sword1.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Great Sword' AND rarity == 1);
UPDATE items SET icon_name = 'great_sword2.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Great Sword' AND rarity == 2);
UPDATE items SET icon_name = 'great_sword3.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Great Sword' AND rarity == 3);
UPDATE items SET icon_name = 'great_sword4.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Great Sword' AND rarity == 4);
UPDATE items SET icon_name = 'great_sword5.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Great Sword' AND rarity == 5);
UPDATE items SET icon_name = 'great_sword6.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Great Sword' AND rarity == 6);
UPDATE items SET icon_name = 'great_sword7.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Great Sword' AND rarity == 7);
UPDATE items SET icon_name = 'great_sword8.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Great Sword' AND rarity == 8);
UPDATE items SET icon_name = 'great_sword9.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Great Sword' AND rarity == 9);
UPDATE items SET icon_name = 'great_sword10.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Great Sword' AND rarity == 10);

UPDATE items SET icon_name = 'long_sword1.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Long Sword' AND rarity == 1);
UPDATE items SET icon_name = 'long_sword2.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Long Sword' AND rarity == 2);
UPDATE items SET icon_name = 'long_sword3.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Long Sword' AND rarity == 3);
UPDATE items SET icon_name = 'long_sword4.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Long Sword' AND rarity == 4);
UPDATE items SET icon_name = 'long_sword5.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Long Sword' AND rarity == 5);
UPDATE items SET icon_name = 'long_sword6.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Long Sword' AND rarity == 6);
UPDATE items SET icon_name = 'long_sword7.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Long Sword' AND rarity == 7);
UPDATE items SET icon_name = 'long_sword8.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Long Sword' AND rarity == 8);
UPDATE items SET icon_name = 'long_sword9.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Long Sword' AND rarity == 9);
UPDATE items SET icon_name = 'long_sword10.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Long Sword' AND rarity == 10);

UPDATE items SET icon_name = 'sword_and_shield1.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Sword and Shield' AND rarity == 1);
UPDATE items SET icon_name = 'sword_and_shield2.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Sword and Shield' AND rarity == 2);
UPDATE items SET icon_name = 'sword_and_shield3.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Sword and Shield' AND rarity == 3);
UPDATE items SET icon_name = 'sword_and_shield4.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Sword and Shield' AND rarity == 4);
UPDATE items SET icon_name = 'sword_and_shield5.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Sword and Shield' AND rarity == 5);
UPDATE items SET icon_name = 'sword_and_shield6.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Sword and Shield' AND rarity == 6);
UPDATE items SET icon_name = 'sword_and_shield7.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Sword and Shield' AND rarity == 7);
UPDATE items SET icon_name = 'sword_and_shield8.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Sword and Shield' AND rarity == 8);
UPDATE items SET icon_name = 'sword_and_shield9.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Sword and Shield' AND rarity == 9);
UPDATE items SET icon_name = 'sword_and_shield10.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Sword and Shield' AND rarity == 10);

UPDATE items SET icon_name = 'dual_blades1.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Dual Blades' AND rarity == 1);
UPDATE items SET icon_name = 'dual_blades2.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Dual Blades' AND rarity == 2);
UPDATE items SET icon_name = 'dual_blades3.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Dual Blades' AND rarity == 3);
UPDATE items SET icon_name = 'dual_blades4.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Dual Blades' AND rarity == 4);
UPDATE items SET icon_name = 'dual_blades5.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Dual Blades' AND rarity == 5);
UPDATE items SET icon_name = 'dual_blades6.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Dual Blades' AND rarity == 6);
UPDATE items SET icon_name = 'dual_blades7.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Dual Blades' AND rarity == 7);
UPDATE items SET icon_name = 'dual_blades8.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Dual Blades' AND rarity == 8);
UPDATE items SET icon_name = 'dual_blades9.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Dual Blades' AND rarity == 9);
UPDATE items SET icon_name = 'dual_blades10.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Dual Blades' AND rarity == 10);

UPDATE items SET icon_name = 'hammer1.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Hammer' AND rarity == 1);
UPDATE items SET icon_name = 'hammer2.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Hammer' AND rarity == 2);
UPDATE items SET icon_name = 'hammer3.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Hammer' AND rarity == 3);
UPDATE items SET icon_name = 'hammer4.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Hammer' AND rarity == 4);
UPDATE items SET icon_name = 'hammer5.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Hammer' AND rarity == 5);
UPDATE items SET icon_name = 'hammer6.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Hammer' AND rarity == 6);
UPDATE items SET icon_name = 'hammer7.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Hammer' AND rarity == 7);
UPDATE items SET icon_name = 'hammer8.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Hammer' AND rarity == 8);
UPDATE items SET icon_name = 'hammer9.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Hammer' AND rarity == 9);
UPDATE items SET icon_name = 'hammer10.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Hammer' AND rarity == 10);

UPDATE items SET icon_name = 'hunting_horn1.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Hunting Horn' AND rarity == 1);
UPDATE items SET icon_name = 'hunting_horn2.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Hunting Horn' AND rarity == 2);
UPDATE items SET icon_name = 'hunting_horn3.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Hunting Horn' AND rarity == 3);
UPDATE items SET icon_name = 'hunting_horn4.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Hunting Horn' AND rarity == 4);
UPDATE items SET icon_name = 'hunting_horn5.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Hunting Horn' AND rarity == 5);
UPDATE items SET icon_name = 'hunting_horn6.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Hunting Horn' AND rarity == 6);
UPDATE items SET icon_name = 'hunting_horn7.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Hunting Horn' AND rarity == 7);
UPDATE items SET icon_name = 'hunting_horn8.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Hunting Horn' AND rarity == 8);
UPDATE items SET icon_name = 'hunting_horn9.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Hunting Horn' AND rarity == 9);
UPDATE items SET icon_name = 'hunting_horn10.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Hunting Horn' AND rarity == 10);

UPDATE items SET icon_name = 'lance1.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Lance' AND rarity == 1);
UPDATE items SET icon_name = 'lance2.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Lance' AND rarity == 2);
UPDATE items SET icon_name = 'lance3.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Lance' AND rarity == 3);
UPDATE items SET icon_name = 'lance4.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Lance' AND rarity == 4);
UPDATE items SET icon_name = 'lance5.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Lance' AND rarity == 5);
UPDATE items SET icon_name = 'lance6.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Lance' AND rarity == 6);
UPDATE items SET icon_name = 'lance7.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Lance' AND rarity == 7);
UPDATE items SET icon_name = 'lance8.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Lance' AND rarity == 8);
UPDATE items SET icon_name = 'lance9.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Lance' AND rarity == 9);
UPDATE items SET icon_name = 'lance10.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Lance' AND rarity == 10);

UPDATE items SET icon_name = 'gunlance1.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Gunlance' AND rarity == 1);
UPDATE items SET icon_name = 'gunlance2.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Gunlance' AND rarity == 2);
UPDATE items SET icon_name = 'gunlance3.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Gunlance' AND rarity == 3);
UPDATE items SET icon_name = 'gunlance4.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Gunlance' AND rarity == 4);
UPDATE items SET icon_name = 'gunlance5.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Gunlance' AND rarity == 5);
UPDATE items SET icon_name = 'gunlance6.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Gunlance' AND rarity == 6);
UPDATE items SET icon_name = 'gunlance7.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Gunlance' AND rarity == 7);
UPDATE items SET icon_name = 'gunlance8.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Gunlance' AND rarity == 8);
UPDATE items SET icon_name = 'gunlance9.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Gunlance' AND rarity == 9);
UPDATE items SET icon_name = 'gunlance10.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Gunlance' AND rarity == 10);

UPDATE items SET icon_name = 'switch_axe1.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Switch Axe' AND rarity == 1);
UPDATE items SET icon_name = 'switch_axe2.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Switch Axe' AND rarity == 2);
UPDATE items SET icon_name = 'switch_axe3.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Switch Axe' AND rarity == 3);
UPDATE items SET icon_name = 'switch_axe4.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Switch Axe' AND rarity == 4);
UPDATE items SET icon_name = 'switch_axe5.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Switch Axe' AND rarity == 5);
UPDATE items SET icon_name = 'switch_axe6.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Switch Axe' AND rarity == 6);
UPDATE items SET icon_name = 'switch_axe7.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Switch Axe' AND rarity == 7);
UPDATE items SET icon_name = 'switch_axe8.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Switch Axe' AND rarity == 8);
UPDATE items SET icon_name = 'switch_axe9.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Switch Axe' AND rarity == 9);
UPDATE items SET icon_name = 'switch_axe10.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Switch Axe' AND rarity == 10);

UPDATE items SET icon_name = 'charge_blade1.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Charge Blade' AND rarity == 1);
UPDATE items SET icon_name = 'charge_blade2.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Charge Blade' AND rarity == 2);
UPDATE items SET icon_name = 'charge_blade3.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Charge Blade' AND rarity == 3);
UPDATE items SET icon_name = 'charge_blade4.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Charge Blade' AND rarity == 4);
UPDATE items SET icon_name = 'charge_blade5.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Charge Blade' AND rarity == 5);
UPDATE items SET icon_name = 'charge_blade6.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Charge Blade' AND rarity == 6);
UPDATE items SET icon_name = 'charge_blade7.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Charge Blade' AND rarity == 7);
UPDATE items SET icon_name = 'charge_blade8.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Charge Blade' AND rarity == 8);
UPDATE items SET icon_name = 'charge_blade9.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Charge Blade' AND rarity == 9);
UPDATE items SET icon_name = 'charge_blade10.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Charge Blade' AND rarity == 10);

UPDATE items SET icon_name = 'insect_glaive1.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Insect Glaive' AND rarity == 1);
UPDATE items SET icon_name = 'insect_glaive2.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Insect Glaive' AND rarity == 2);
UPDATE items SET icon_name = 'insect_glaive3.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Insect Glaive' AND rarity == 3);
UPDATE items SET icon_name = 'insect_glaive4.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Insect Glaive' AND rarity == 4);
UPDATE items SET icon_name = 'insect_glaive5.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Insect Glaive' AND rarity == 5);
UPDATE items SET icon_name = 'insect_glaive6.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Insect Glaive' AND rarity == 6);
UPDATE items SET icon_name = 'insect_glaive7.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Insect Glaive' AND rarity == 7);
UPDATE items SET icon_name = 'insect_glaive8.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Insect Glaive' AND rarity == 8);
UPDATE items SET icon_name = 'insect_glaive9.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Insect Glaive' AND rarity == 9);
UPDATE items SET icon_name = 'insect_glaive10.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Insect Glaive' AND rarity == 10);

UPDATE items SET icon_name = 'light_bowgun1.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Light Bowgun' AND rarity == 1);
UPDATE items SET icon_name = 'light_bowgun2.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Light Bowgun' AND rarity == 2);
UPDATE items SET icon_name = 'light_bowgun3.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Light Bowgun' AND rarity == 3);
UPDATE items SET icon_name = 'light_bowgun4.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Light Bowgun' AND rarity == 4);
UPDATE items SET icon_name = 'light_bowgun5.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Light Bowgun' AND rarity == 5);
UPDATE items SET icon_name = 'light_bowgun6.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Light Bowgun' AND rarity == 6);
UPDATE items SET icon_name = 'light_bowgun7.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Light Bowgun' AND rarity == 7);
UPDATE items SET icon_name = 'light_bowgun8.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Light Bowgun' AND rarity == 8);
UPDATE items SET icon_name = 'light_bowgun9.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Light Bowgun' AND rarity == 9);
UPDATE items SET icon_name = 'light_bowgun10.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Light Bowgun' AND rarity == 10);

UPDATE items SET icon_name = 'heavy_bowgun1.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Heavy Bowgun' AND rarity == 1);
UPDATE items SET icon_name = 'heavy_bowgun2.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Heavy Bowgun' AND rarity == 2);
UPDATE items SET icon_name = 'heavy_bowgun3.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Heavy Bowgun' AND rarity == 3);
UPDATE items SET icon_name = 'heavy_bowgun4.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Heavy Bowgun' AND rarity == 4);
UPDATE items SET icon_name = 'heavy_bowgun5.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Heavy Bowgun' AND rarity == 5);
UPDATE items SET icon_name = 'heavy_bowgun6.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Heavy Bowgun' AND rarity == 6);
UPDATE items SET icon_name = 'heavy_bowgun7.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Heavy Bowgun' AND rarity == 7);
UPDATE items SET icon_name = 'heavy_bowgun8.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Heavy Bowgun' AND rarity == 8);
UPDATE items SET icon_name = 'heavy_bowgun9.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Heavy Bowgun' AND rarity == 9);
UPDATE items SET icon_name = 'heavy_bowgun10.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Heavy Bowgun' AND rarity == 10);

UPDATE items SET icon_name = 'bow1.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Bow' AND rarity == 1);
UPDATE items SET icon_name = 'bow2.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Bow' AND rarity == 2);
UPDATE items SET icon_name = 'bow3.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Bow' AND rarity == 3);
UPDATE items SET icon_name = 'bow4.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Bow' AND rarity == 4);
UPDATE items SET icon_name = 'bow5.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Bow' AND rarity == 5);
UPDATE items SET icon_name = 'bow6.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Bow' AND rarity == 6);
UPDATE items SET icon_name = 'bow7.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Bow' AND rarity == 7);
UPDATE items SET icon_name = 'bow8.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Bow' AND rarity == 8);
UPDATE items SET icon_name = 'bow9.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Bow' AND rarity == 9);
UPDATE items SET icon_name = 'bow10.png' WHERE _id IN (SELECT _id FROM weapons WHERE wtype == 'Bow' AND rarity == 10);

UPDATE items SET icon_name = 'arms1.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Arms' AND rarity == 1);
UPDATE items SET icon_name = 'arms2.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Arms' AND rarity == 2);
UPDATE items SET icon_name = 'arms3.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Arms' AND rarity == 3);
UPDATE items SET icon_name = 'arms4.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Arms' AND rarity == 4);
UPDATE items SET icon_name = 'arms5.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Arms' AND rarity == 5);
UPDATE items SET icon_name = 'arms6.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Arms' AND rarity == 6);
UPDATE items SET icon_name = 'arms7.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Arms' AND rarity == 7);
UPDATE items SET icon_name = 'arms8.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Arms' AND rarity == 8);
UPDATE items SET icon_name = 'arms9.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Arms' AND rarity == 9);
UPDATE items SET icon_name = 'arms10.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Arms' AND rarity == 10);

UPDATE items SET icon_name = 'body1.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Body' AND rarity == 1);
UPDATE items SET icon_name = 'body2.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Body' AND rarity == 2);
UPDATE items SET icon_name = 'body3.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Body' AND rarity == 3);
UPDATE items SET icon_name = 'body4.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Body' AND rarity == 4);
UPDATE items SET icon_name = 'body5.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Body' AND rarity == 5);
UPDATE items SET icon_name = 'body6.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Body' AND rarity == 6);
UPDATE items SET icon_name = 'body7.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Body' AND rarity == 7);
UPDATE items SET icon_name = 'body8.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Body' AND rarity == 8);
UPDATE items SET icon_name = 'body9.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Body' AND rarity == 9);
UPDATE items SET icon_name = 'body10.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Body' AND rarity == 10);

UPDATE items SET icon_name = 'waist1.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Waist' AND rarity == 1);
UPDATE items SET icon_name = 'waist2.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Waist' AND rarity == 2);
UPDATE items SET icon_name = 'waist3.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Waist' AND rarity == 3);
UPDATE items SET icon_name = 'waist4.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Waist' AND rarity == 4);
UPDATE items SET icon_name = 'waist5.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Waist' AND rarity == 5);
UPDATE items SET icon_name = 'waist6.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Waist' AND rarity == 6);
UPDATE items SET icon_name = 'waist7.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Waist' AND rarity == 7);
UPDATE items SET icon_name = 'waist8.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Waist' AND rarity == 8);
UPDATE items SET icon_name = 'waist9.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Waist' AND rarity == 9);
UPDATE items SET icon_name = 'waist10.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Waist' AND rarity == 10);

UPDATE items SET icon_name = 'legs1.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Legs' AND rarity == 1);
UPDATE items SET icon_name = 'legs2.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Legs' AND rarity == 2);
UPDATE items SET icon_name = 'legs3.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Legs' AND rarity == 3);
UPDATE items SET icon_name = 'legs4.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Legs' AND rarity == 4);
UPDATE items SET icon_name = 'legs5.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Legs' AND rarity == 5);
UPDATE items SET icon_name = 'legs6.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Legs' AND rarity == 6);
UPDATE items SET icon_name = 'legs7.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Legs' AND rarity == 7);
UPDATE items SET icon_name = 'legs8.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Legs' AND rarity == 8);
UPDATE items SET icon_name = 'legs9.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Legs' AND rarity == 9);
UPDATE items SET icon_name = 'legs10.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Legs' AND rarity == 10);

UPDATE items SET icon_name = 'head1.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Head' AND rarity == 1);
UPDATE items SET icon_name = 'head2.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Head' AND rarity == 2);
UPDATE items SET icon_name = 'head3.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Head' AND rarity == 3);
UPDATE items SET icon_name = 'head4.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Head' AND rarity == 4);
UPDATE items SET icon_name = 'head5.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Head' AND rarity == 5);
UPDATE items SET icon_name = 'head6.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Head' AND rarity == 6);
UPDATE items SET icon_name = 'head7.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Head' AND rarity == 7);
UPDATE items SET icon_name = 'head8.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Head' AND rarity == 8);
UPDATE items SET icon_name = 'head9.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Head' AND rarity == 9);
UPDATE items SET icon_name = 'head10.png' WHERE _id IN (SELECT _id FROM armor WHERE slot == 'Head' AND rarity == 10);